services:
  - type: web
    name: lab2-frontend
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    staticPublishPath: ./dist
